### ISSUE TITLE
Null Check Required Before VariableName in... check

### ISSUE THREAD

**Issue by jakobo** [typed-graphql-builder/typed-graphql-builder#40]
Currently, tgqlb isn't checking for null in its args before attempting to look inside a collection with `VariableName in`, generating the following error:

```
Runtime.ExitError
2022-10-20T19:08:28.758Z	ca0f8024-9543-4f07-8e50-a71fadcfc033	ERROR	TypeError: Cannot use 'in' operator to search for ' $1fcbcbff-3e78-462f-b45c-668a3e09bfd8' in null
    at stringifyArgs (/var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:228:34)
    at /var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:246:40
    at Array.map (<anonymous>)
    at stringifyArgs (/var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:241:65)
    at /var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:246:40
    at Array.map (<anonymous>)
    at stringifyArgs (/var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:241:65)
    at extractTextAndVars (/var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:256:33)
    at extractTextAndVars (/var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:262:31)
    at fieldToQuery (/var/task/services/for.taskless.io/.next/server/pages/api/graphql.js:278:22)
```

Fix is just to move our null check earlier in `stringifyArgs` (preamble)

**Comment by jakobo** [comment]
Sample `field` that triggers the error during `fieldToQuery`. Call is going to a Hasura instance. Culprit is likely an attempt to set a field to null.

```json
"_set": {
  "nextRun": null
}
```

Full JSON below

```json
{
  "name": "mutation",
  "options": {
    "selection": [
      {
        "name": "updateJob",
        "options": {
          "argTypes": {
            "_inc": "job_inc_input",
            "_set": "job_set_input",
            "pk_columns": "job_pk_columns_input!"
          },
          "args": {
            "pk_columns": {
              "id": {
                "isRequired": true,
                " $1fcbcbff-3e78-462f-b45c-668a3e09bfd8": "id"
              }
            },
            "_set": {
              "enabled": false
            }
          },
          "selection": [
            {
              "name": "id",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "createdAt",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "name",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "enabled",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "updatedAt",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "queueId",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "body",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "endpoint",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "headers",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "retries",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "runAt",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "runEvery",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "method",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "timezone",
              "options": {},
              "kind": "field",
              "alias": null
            }
          ]
        },
        "kind": "field",
        "alias": null
      },
      {
        "name": "updateJobSummary",
        "options": {
          "argTypes": {
            "_inc": "jobSummary_inc_input",
            "_set": "jobSummary_set_input",
            "pk_columns": "jobSummary_pk_columns_input!"
          },
          "args": {
            "pk_columns": {
              "jobId": {
                "isRequired": true,
                " $1fcbcbff-3e78-462f-b45c-668a3e09bfd8": "id"
              }
            },
            "_set": {
              "nextRun": null
            }
          },
          "selection": [
            {
              "name": "jobId",
              "options": {},
              "kind": "field",
              "alias": null
            },
            {
              "name": "nextRun",
              "options": {},
              "kind": "field",
              "alias": null
            }
          ]
        },
        "kind": "field",
        "alias": null
      }
    ]
  },
  "kind": "field",
  "alias": null
}
```
